In [15]:
import cv2

In [2]:
img = cv2.imread('galaxy.jpg', 0)
print(img)

[[14 18 14 ... 20 15 16]
 [12 16 12 ... 20 15 17]
 [12 13 16 ... 14 24 21]
 ...
 [ 0  0  0 ...  5  8 14]
 [ 0  0  0 ...  2  3  9]
 [ 1  1  1 ...  1  1  3]]


In [3]:
print(img.shape)

(1485, 990)


In [4]:
print(img.ndim)

2


In [5]:
rez_img = cv2.resize(img,(int(img.shape[1]/2), int(img.shape[0]/2)))

In [6]:
cv2.imshow('galaxy.jpg', rez_img)
cv2.imwrite("galaxy_resized.jpg", rez_img)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [7]:
img2 = cv2.imread('sample_images/kangaroos-rain-australia_71370_990x742.jpg')
img2

array([[[227, 252, 255],
        [228, 253, 255],
        [228, 253, 255],
        ...,
        [ 55,  85, 120],
        [ 54,  84, 119],
        [ 42,  72, 107]],

       [[227, 252, 255],
        [227, 252, 255],
        [228, 253, 255],
        ...,
        [ 51,  81, 116],
        [ 34,  64,  99],
        [ 34,  64,  99]],

       [[227, 252, 255],
        [227, 252, 255],
        [227, 252, 255],
        ...,
        [ 27,  57,  92],
        [ 24,  54,  89],
        [ 27,  57,  92]],

       ...,

       [[ 59, 103, 162],
        [ 46,  90, 149],
        [ 62, 106, 167],
        ...,
        [ 58, 114, 185],
        [ 56, 112, 183],
        [ 56, 113, 182]],

       [[ 74, 118, 179],
        [ 62, 106, 167],
        [ 67, 111, 172],
        ...,
        [ 70, 128, 200],
        [ 75, 133, 205],
        [ 72, 131, 201]],

       [[ 60, 104, 165],
        [ 60, 104, 165],
        [ 58, 102, 163],
        ...,
        [ 76, 134, 206],
        [ 82, 140, 212],
        [ 78, 136, 208]]

In [8]:
res_img2 = cv2.resize(img2, (int(img.shape[1]/2), int(img.shape[0]/2)))
cv2.imshow('sample_images/kangaroos-rain-australia_71370_990x742.jpg', res_img2)
cv2.imwrite('Img2_resize.jpg', res_img2)
cv2.waitKey(5000)
cv2.destroyAllWindows()


In [9]:
img3 = cv2.imread('sample_images/Lighthouse.jpg', 0)
img3

array([[141, 140, 140, ..., 198, 198, 197],
       [143, 141, 139, ..., 197, 199, 197],
       [140, 141, 141, ..., 198, 200, 197],
       ...,
       [ 12,  13,  12, ...,  25,  18,  13],
       [ 14,  16,  17, ...,  17,  14,  14],
       [  8,  12,  17, ...,  11,   9,  16]], dtype=uint8)

In [10]:
img3.shape

(768, 1024)

In [ ]:
res_img3 = cv2.resize(img3, (int(img.shape[1]/2), int(img.shape[0]/2)))
cv2.imshow('sample_images/Lighthouse.jpg', res_img3)
cv2.imwrite('img3_resize.jpg', res_img3)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [ ]:
img4 = cv2.imread('sample_images/Moon sinking, sun rising.jpg', 0)
img4

In [ ]:
img4.shape

In [ ]:
res_img4 = cv2.resize(img4,(int(img4.shape[1]/2), int(img4.shape[1]/2)))
cv2.imshow('sample_images/Moon sinking, sun rising.jpg', res_img4)
cv2.imwrite('img4_resize.jpg', res_img4)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [28]:
face_cascade = cv2.CascadeClassifier("Files/haarcascade_frontalface_default.xml")
img = cv2.imread("Files/news.jpg")
gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray_image,scaleFactor=1.5, minNeighbors=5)

for x,y,w,h in faces:
    img=cv2.rectangle(img,(x,y), (x+w,y+h), (0,255,00), 3)

print(type(faces))
print(faces)


cv2.imshow("Gray", img)
cv2.waitKey(5000)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[ 43 214 122 122]]
